set_key_lock:
  name: Set key lock
  description: Sets device key access.
  target:
    entity:
      domain: climate
  fields:
    key_lock:
      name: Key lock
      description: New value for key access.
      required: true
      default: 'unlocked'
      selector:
        select:
          options:
            - 'unlocked'
            - 'power_unlocked'
            - 'locked'

set_hvac_mode:
  name: Set hvac mode
  description: Sets hvac mode.
  target:
    entity:
      domain: climate
  fields:
    hvac_mode:
      name: Hvac mode
      description: New value for hvac mode.
      required: true
      default: 'auto'
      example: 'auto'
      selector:
        select:
          options:
            - 'off'
            - 'heat'
            - 'auto'

set_temperature:
  name: Set temperature
  description: Sets target temperature.
  target:
    entity:
      domain: climate
  fields:
    temperature:
      name: Temperature
      description: New target temperature.
      required: true
      default: 22
      example: '22'
      selector:
        number:
          min: 10
          max: 40
          unit_of_measurement: "ºC"

turn_on:
  name: Turn on
  description: Turn climate device on.
  target:
    entity:
      domain: climate

turn_off:
  name: Turn off
  description: Turn climate device off.
  target:
    entity:
      domain: climate
      
set_hysteresis:
  name: Set hysteresis
  description: Sets hysteresis.
  target:
    entity:
      domain: climate
  fields:
    hysteresis:
      name: Hysteresis
      description: New value for hysteresis.
      required: true
      default: '1'
      selector:
        select:
          options:
            - '0.5'
            - '1'

set_calibration:
  name: Set calibration
  description: Sets calibration.
  target:
    entity:
      domain: climate
  fields:
    calibration:
      name: Calibration
      description: New value for calibration.
      required: true
      default: 0
      selector:
        number:
          min: -5.0
          max: 5.0
          step: 0.1

set_cooling_max_temp:
  name: Set cooling maximum temperature
  description: Sets cooling maximum admitted temperature.
  target:
    entity:
      domain: climate
  fields:
    max_temp:
      name: Cooling maximum temperature
      description: New value for cooling maximum admitted temperature.
      required: true
      default: 40
      selector:
        number:
          min: 10
          max: 40
          unit_of_measurement: 'ºC'

set_cooling_min_temp:
  name: Set cooling minimum temperature
  description: Sets cooling minimum admitted temperature.
  target:
    entity:
      domain: climate
  fields:
    max_temp:
      name: Cooling minimum temperature
      description: New value for cooling minimum admitted temperature.
      required: true
      default: 10
      selector:
        number:
          min: 10
          max: 40
          unit_of_measurement: 'ºC'

set_heating_max_temp:
  name: Set heating maximum temperature
  description: Sets heating maximum admitted temperature.
  target:
    entity:
      domain: climate
  fields:
    max_temp:
      name: Heating maximum temperature
      description: New value for heating maximum admitted temperature.
      required: true
      default: 40
      selector:
        number:
          min: 10
          max: 40
          unit_of_measurement: 'ºC'

set_heating_min_temp:
  name: Set heating minimum temperature
  description: Sets heating minimum admitted temperature.
  target:
    entity:
      domain: climate
  fields:
    max_temp:
      name: Heating minimum temperature
      description: New value for heating minimum admitted temperature.
      required: true
      default: 10
      selector:
        number:
          min: 10
          max: 40
          unit_of_measurement: 'ºC'

set_fan_control:
  name: Set fan control
  description: Sets fan stop when target temperature reached.
  target:
    entity:
      domain: climate
  fields:
    fan_control:
      name: Fan Control
      description: New value for fan control.
      required: true
      default: 'off'
      selector:
        select:
          options:
            - 'on'
            - 'off'

set_frost_protection:
  name: Set frost protection
  description: Sets frost protection.
  target:
    entity:
      domain: climate
  fields:
    frost_protection:
      name: Frost protection
      description: New value for frost protection.
      required: true
      default: 'off'
      selector:
        select:
          options:
            - 'on'
            - 'off'

set_time:
  name: Set time
  description: Sets time (or time now).
  target:
    entity:
      domain: climate
  fields:
    now:
      name: Now
      description: Sets time now.
      default: true
      example: 'true'
      selector:
        boolean:
    time:
      description: Sets time.
      default: '08:00:00'
      example: '08:00:00'
      selector:
        text:
    weekday:
      name: Weekday
      description: Set week day (1 - Monday, 7 Sunday).
      default: 1
      example: '1'
      selector:
        number:
          min: 1
          max: 7

set_schedule:
  name: Set schedule
  description: Sets schedule.
  target:
    entity:
      domain: climate
  fields:
    weekly_schedule:
      name: Weekly schedule
      description: New value weekly schedule.
      default: 'manual'
      example: 'manual'
      selector:
        select:
          options:
            - 'manual'
            - '12345'
            - '123456'
            - '1234567'
    period1_enabled:
      name: Period1 enable
      description: Enables first period.
      default: true
      example: 'true'
      selector:
        boolean:
    period1_start_time:
      name: Period1 start time
      description: Sets start time for the 1st period.
      default: '08:00'
      example: '08:00'
      selector:
        text:
    period1_end_time:
      name: Period1 end time
      description: Sets end time for the 1st period.
      default: '11:30'
      example: '11:30'
      selector:
        text:
    period2_enabled:
      name: Period2 enable
      description: Enables second period.
      default: true
      example: 'true'
      selector:
        boolean:
    period2_start_time:
      name: Period2 start time
      description: Sets start time for the 2nd period.
      default: '12:30'
      example: '12:30'
      selector:
        text:
    period2_end_time:
      name: Period2 end time
      description: Sets end time for the 2nd period.
      default: '17:00'
      example: '17:00'
      selector:
        text:
