set_key_lock:
  name: Set key lock
  description: Set the key lock mode.
  target:
    entity:
      domain: select
  fields:
    key_lock:
      name: Key lock
      description: The key lock mode to set (Unlocked, Locked Except Power, or Locked).
      required: true
      example: "Locked Except Power"
      selector:
        select:
          options:
            - "Unlocked"
            - "Locked Except Power"
            - "Locked"

set_hvac_mode:
  name: Set HVAC mode
  description: Set the HVAC mode.
  target:
    entity:
      domain: climate
  fields:
    hvac_mode:
      name: HVAC mode
      description: The HVAC mode to set (off, heat, cool, or fan_only).
      required: true
      example: "heat"
      selector:
        select:
          options:
            - "off"
            - "heat"
            - "cool"
            - "fan_only"

set_fan_mode:
  name: Set fan mode
  description: Set the fan mode.
  target:
    entity:
      domain: climate
  fields:
    fan_mode:
      name: Fan mode
      description: The fan mode to set (low, medium, high, or auto).
      required: true
      example: "low"
      selector:
        select:
          options:
            - "low"
            - "medium"
            - "high"
            - "auto"

set_preset_mode:
  name: Set preset mode
  description: Set the preset mode for the Hysen climate entity.
  target:
    entity:
      domain: climate
  fields:
    preset_mode:
      name: Preset mode
      description: The preset mode to set (Today, Workdays, Sixdays, or Fullweek).
      required: true
      example: "Today"
      selector:
        select:
          options:
            - "Today"
            - "Workdays"
            - "Sixdays"
            - "Fullweek"

set_temperature:
  name: Set temperature
  description: Set the target temperature.
  target:
    entity:
      domain: climate
  fields:
    temperature:
      name: Temperature
      description: The target temperature to set (between 10 and 40°C).
      required: true
      example: 22
      selector:
        number:
          min: 10
          max: 40
          step: 1
          unit_of_measurement: "°C"

turn_on:
  name: Turn on
  description: Turn the climate entity on.
  target:
    entity:
      domain: climate

turn_off:
  name: Turn off
  description: Turn the climate entity off.
  target:
    entity:
      domain: climate

set_hysteresis:
  name: Set hysteresis
  description: Set the hysteresis value.
  target:
    entity:
      domain: select
  fields:
    hysteresis:
      name: Hysteresis
      description: The hysteresis value to set (0.5 or 1.0°C).
      required: true
      example: "0.5"
      selector:
        select:
          options:
            - "0.5"
            - "1.0"

set_calibration:
  name: Set calibration
  description: Set the temperature calibration.
  target:
    entity:
      domain: number
  fields:
    calibration:
      name: Calibration
      description: The calibration value to set (between -5.0 and 5.0°C, in 0.1°C steps).
      required: true
      example: -0.5
      selector:
        number:
          min: -5.0
          max: 5.0
          step: 0.1
          unit_of_measurement: "°C"

set_max_temp:
  name: Set max temp
  description: Set the maximum temperature based on HVAC mode.
  target:
    entity:
      domain: number
  fields:
    max_temp:
      name: Max temp
      description: The maximum temperature to set (between 10 and 40°C, must be at least target temperature).
      required: true
      example: 30
      selector:
        number:
          min: 10
          max: 40
          step: 1
          unit_of_measurement: "°C"

set_min_temp:
  name: Set min temp
  description: Set the minimum temperature based on HVAC mode.
  target:
    entity:
      domain: number
  fields:
    min_temp:
      name: Min temp
      description: The minimum temperature to set (between 10 and 40°C, must not exceed target temperature).
      required: true
      example: 18
      selector:
        number:
          min: 10
          max: 40
          step: 1
          unit_of_measurement: "°C"

set_fan_control:
  name: Set fan control
  description: Set the fan control state.
  target:
    entity:
      domain: switch
  fields:
    fan_control:
      name: Fan control
      description: The fan control state to set (on or off).
      required: true
      example: "on"
      selector:
        select:
          options:
            - "on"
            - "off"

set_frost_protection:
  name: Set frost protection
  description: Set the frost protection state.
  target:
    entity:
      domain: switch
  fields:
    frost_protection:
      name: Frost protection
      description: The frost protection state to set (on or off).
      required: true
      example: "on"
      selector:
        select:
          options:
            - "on"
            - "off"

set_time:
  name: Set time
  description: Set the device time and weekday.
  target:
    entity:
      domain: button
  fields:
    device_time:
      name: Device time
      description: The time to set in HH:MM:SS format.
      required: true
      example: "14:30:00"
      selector:
        time: {}
    device_weekday:
      name: Device weekday
      description: The weekday to set (1=Monday to 7=Sunday).
      required: true
      example: 3
      selector:
        number:
          min: 1
          max: 7
          mode: box

set_slot1_start_enable:
  name: Set slot1 start enable
  description: Set the slot 1 start enable state.
  target:
    entity:
      domain: switch
  fields:
    slot1_start_enable:
      name: Slot1 start enable
      description: The slot 1 start enable state to set (on or off).
      required: true
      example: "on"
      selector:
        select:
          options:
            - "on"
            - "off"

set_slot1_stop_enable:
  name: Set slot1 stop enable
  description: Set the slot 1 stop enable state.
  target:
    entity:
      domain: switch
  fields:
    slot1_stop_enable:
      name: Slot1 stop enable
      description: The slot 1 stop enable state to set (on or off).
      required: true
      example: "on"
      selector:
        select:
          options:
            - "on"
            - "off"

set_slot2_start_enable:
  name: Set slot2 start enable
  description: Set the slot 2 start enable state.
  target:
    entity:
      domain: switch
  fields:
    slot2_start_enable:
      name: Slot2 start enable
      description: The slot 2 start enable state to set (on or off).
      required: true
      example: "on"
      selector:
        select:
          options:
            - "on"
            - "off"

set_slot2_stop_enable:
  name: Set slot2 stop enable
  description: Set the slot 2 stop enable state.
  target:
    entity:
      domain: switch
  fields:
    slot2_stop_enable:
      name: Slot2 stop enable
      description: The slot 2 stop enable state to set (on or off).
      required: true
      example: "on"
      selector:
        select:
          options:
            - "on"
            - "off"

set_slot1_start_time:
  name: Set slot1 start time
  description: Set the slot 1 start time.
  target:
    entity:
      domain: time
  fields:
    slot1_start_time:
      name: Slot1 start time
      description: The time to set in HH:MM format.
      required: true
      example: "08:00"
      selector:
        time: {}

set_slot1_stop_time:
  name: Set slot1 stop time
  description: Set the slot 1 stop time.
  target:
    entity:
      domain: time
  fields:
    slot1_stop_time:
      name: Slot1 stop time
      description: The time to set in HH:MM format.
      required: true
      example: "17:00"
      selector:
        time: {}

set_slot2_start_time:
  name: Set slot2 start time
  description: Set the slot 2 start time.
  target:
    entity:
      domain: time
  fields:
    slot2_start_time:
      name: Slot2 start time
      description: The time to set in HH:MM format.
      required: true
      example: "18:00"
      selector:
        time: {}

set_slot2_stop_time:
  name: Set slot2 stop time
  description: Set the slot 2 stop time.
  target:
    entity:
      domain: time
  fields:
    slot2_stop_time:
      name: Slot2 stop time
      description: The time to set in HH:MM format.
      required: true
      example: "22:00"
      selector:
        time: {}
